name: maru

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install pnpm@9.0
        run: npm install -g pnpm@9.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Build (User App)
        run: pnpm turbo run build --filter=./apps/user --continue
